# Generated by Django 5.2.4 on 2025-07-19 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_performance_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.actor')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.performance')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.role')),
            ],
        ),
    ]
